# Experiment configuration
total_epochs: 1
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
sampler: "uniform"
sampler_args:
  - 0.5     # p degree
  - 42      # random seed
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_single_machine'
output_location: 'output'
tensor_board_active: true
clients_per_round: 2
system:
  federator:
    # Use the SERVICE provided by the fl-server to connect
    hostname: '172.18.0.2'
    # Default NIC is eth0
    nic: 'eth0'
  clients:
    amount: 2
# For a simple config is provided in configs/poison.example.yaml
poison:
  seed: 420
  ratio: 0.2
  attack:
    type: "flip"
    config:
      - 5: 3


