{{ $worldsize := (.Values.fltk.worldsize | int) }}
{{ $workercpu := (.Values.worker.cpu | int) }}
{{ $workermemory := (.Values.worker.memory | int) }}

{{- range untilStep 1 (add1 $worldsize | int) 1 }}
{{ $rank := ( . | int)}}
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f ../docker-compose-gcloud.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: client-slow-{{ . }}
  name: client-slow-{{ . }}
spec:
  containers:
    - args:
        - python3
        - -m
        - fltk
        - single
        - configs/cloud_experiment.yaml
        - --rank={{ . }}
      env:
        - name: MASTER_PORT
          value: "5000"
        - name: GLOO_SOCKET_IFNAME
          value: eth0
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: RANK
          value: {{ quote $rank }}
        - name: TP_SOCKET_IFNAME
          value: eth0
        - name: WORLD_SIZE
          value: {{ quote $worldsize }}
      image: gcr.io/cs4290-wouter/fltk:latest
      name: client-slow
      resources:
        limits:
          cpu: {{ $workercpu }}
          # 1 GiB ?
          memory: {{ $workermemory }}
        requests:
          memory: 1500000000
  restartPolicy: Never
status:
  qosClass: Guaranteed
# Helm requires seperation.
---
{{- end }}
